---

- name: Update Immich Containers
  hosts: "Immich_VM's"
  become: true
  tasks:
    - name: Pull latest Immich image
      command: docker compose pull
      args:
        chdir: "{{ compose_path }}"

    - name: Restart Immich stack
      command: docker compose up -d
      args:
        chdir: "{{ compose_path }}"

    - name: Remove old images
      command: docker image prune -f
